name: adaptable_screen
description: The plug-in scales sizes based on the size of the UIDesign prototypes and the windows the components are being placed into.
version: 0.0.3
repository: https://github.com/Sthaynny/adaptable_screen
issue_tracker: https://github.com/Sthaynny/adaptable_screen/issues
homepage: https://github.com/Sthaynny/adaptable_screen

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:


